// src/components/About.js

import React from "react"
import "./about.scss"

const About = () => {
  return (
    <section className="about">
      <h1>​Gurdwara Charan Kamal Sahib, Bakhta (Jasrota)</h1>
      <h2>VISIT OF GURU NANAK DEV JI TO VILLAGE BAKHTA (JASROTA) </h2>
    <p lang="en" dir="rtl">Guru Nanak Dev Ji, the founder of the Sikh religion was born to Kalu Chand Mehta and mata Tripta on 15 April 1469 AD in the village of Talwandi near Lahore. Pandit Hardyal, the family's Brahmin priest was asked to make the horoscope of the child. The pandit and the midwife (Daulatan) agreed that the child had an exceptional aura. The horscope prepared by Pandit Hardyal predicted that Hindus and Muslims alike would acknowledge Nanak as a Philosopher-teacher and that he in turn would make no distinction between them. Guru Nanak was a precocious child. At the age of five he started asking questions about the purpose of life. During his stay at Sultanpur, a Muslim minstrel Mardana joined him and  the two organised singing of hymns in the town. Early morning Guru Nanak used to bathe and then attend to his daily durbar. During one of these early morning ablutions by the river, Guru Nanak had his first mystic experience (Communication with the God). He was taken in a vision to God's presence. He was offered a cup of nectar to drink and God charged him with the mission to pray and teach mankind how to pray and to get them rid of superstitions, idol worship etc. Guru Nanak hereafter travelled extensively within the country and as far as Ceylon and Baghdad. Guru Nanak's first travel (Udassi) has been recorded to East (Mathura, Benares, Gaya, Bengal Assam to name a few) and on return he stopped at Jaggannath Puri. After this Guru Nanak spent some years in Punjab. His second travel was towards south, Tamil land and Ceylon and back via western coast. The Third travel was to North as far as Tibet Ladakh and Jammu and Kashmir. The Guru's Last travel was to Mecca and Medina as far as Baghdad.</p>
       <h2>ACCOUNT OF GURU NANAK'S THIRD UDASSI</h2>
    <p lang="en" dir="rtl">​The account of Guru Nanak Dev Ji's travel during the third Udassi has been written by various accomplished historians and writers like Giani Gian Singh Ji, Bhai Santokh Singh Ji, Bhai Kahan Singh Nabha, Max Arthur Macauliffe , Bhai Veer Singh Ji and many others. Guru Nanak Dev Ji commenced his third Udassi from Punjab and he travelled extensively to the north. Some of the important Places visited by Guru Nanak during his third Udassi ​ are Gurdaspur, Kangra, Chamba, KuIlu, ManiKaran, Kiratpur, Pinjor, Garhwal, Dehradun, Mansuri, Chakrat, Binsar, Kashi, Yamnotri, Gangotri, Gawumukh, Badrinath, Himalyas (several peaks including Hemkunt Parbat), Parvesh to Sachkhand, Nanak Matta, Sumair Parbat, Ranikhet, Almora, Nainital, Ayodhya, Gorakhpur, Janakpur, Nepal (Kathmandu), Sikkim, Bhutan, China, Tibet, Lahasa, Man Sarovar, Kailash Parbat, Yarkand, Mantali, Ladakh, Sarkot ,Gilgit, Skardu ,Srinagar( Hariparbat and Shankracharya hill), Awantipur, Bij Behara, Anantnag, Mattan ,Amarnath, Kishtwar, Bhaderwa, Chenani, Vaishnodevi, Jammu (Jamvant Di Gufa now called Peer Kho, Mandir in Bahu Fort) Parmandal, Mansar Surinsar, Jasrota, Madhopur . Guru Nanak Dev Ji is supposed to have entered the state of Jammu and Kashimr from Ladakh.</p>
    <h2>GURU NANAK DEV JI'S STAY AT BAKHTA,JASROTA </h2>
    <p lang="en" dir="rtl">Guru Nanak Dev Ji after visiting Purmandal, Mansar and Surinsar came to Jasrota. Whilst his stay at Jasrota (village Bakhta) district Kathua, he gave religious discourses to the people and made them aware about the true Lord and the right way to worship Him. Master Gurnam Singh of village Jasrota whilst serving in village Bakhta came to know about the visit of Guru Nanak Dev Ji to this place. He wrote to the SGPC in the year 1998 about this. The Sikh research forum after carrying out a study confirmed the fact that Guru Nanak Dev Ji visited this place. In the year 2012 commodore Dalbir Singh Ji Sodhi (Author of the book "Historical Sikh Shrines of Jammu and Kashmir") along with Giani Swaran Siingh Ji and Master Gurnam Singh Ji of Jasrota visited village Bakhta. During interaction with the local community and Thakur Hurmat Singh Chambyal, they were shown the Asthan where Guru Nanak Dev Ji is supposed to have sat under a Pipal tree. The Asthan is revered by the people of this area and refered to as Baba Nanak's Asthan. The people of the area consider this Asthan along with the Pipal tree to be very sacred. Subsequently discussions were held with Thakur Hurmat Singh Ji, and other villagers like Jagdish singh, Bashasher Singh, Kuldeep and after protacted discussions was able to convince them to offer this Asthan for construction of a Gurdwara to commemorate the visit of Guru Nanak Dev ji to this place. Understanding the sanctity of this Asthan, Thakur Hurmat Singh decided to donate one kanal of land in the memory of his late son Kanwal Narinder Singh Chambyal for construction of the Historical Gurdwara. In order to pursue the matter further a trust of religious minded intellectual members from various quarters was formed. However, keeping in view the sentiments of the Sikh Sangat, a conscious decision was taken by the trust that the land donated by Thakur Hurmat Singh ji and 3 kanal 15 marla land purchased by the trust (Total 4 kanal 15 marla) is registered in the name of Sri Guru Granth Sahib Gurdwara Charan Kamal Sri Guru Nanak Dev. 
       Accordingly, Sri Guru Nanak Dev Ji Charitable and Religious trust took on the responsibility of constructing a Historical Gurdwara at this Asthan. With the support of the Sikh Sangat of Jasrota as well as the residents of Bakhta Village a beautiful permanent structure  as been co-trusted or installation of Sri Guru Granth Sahib Ji. Baba Jasbir Singh Beera Ji (disciple of late Baba Harbhans Singh Ji Panth Rattan Kar Sewa Wale) who has been instrumental in construction of various historical Sikh Shrines in Jammu & Kashmir has started the construction of Gurudwara Sahib. Baba Beera Ji also provided support in construction of the Langer hall and necessary accommodation for the Granthis) Sikh Sangat from all over Jammu and Kashmir and other parts of India and abroad as well as Sangat from other communities are requested to visit this important historical Sikh Shrine and obtain the Blessings of the Almighty.</p>
    <h3>Waheguru Ji Ka Khalsa, 
        Waheguru Ji Ki Fateh </h3> 
    </section>
    
  )
}

export default About
